// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: github.com/johnsiilver/golib/ipc/uds/highlevel/proto/stream/internal/proto/stream.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Request a quote from the server.
type MsgIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgIn) Reset() {
	*x = MsgIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIn) ProtoMessage() {}

func (x *MsgIn) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIn.ProtoReflect.Descriptor instead.
func (*MsgIn) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *MsgIn) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgIn) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Response for a quote.
type MsgOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgOut) Reset() {
	*x = MsgOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgOut) ProtoMessage() {}

func (x *MsgOut) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgOut.ProtoReflect.Descriptor instead.
func (*MsgOut) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *MsgOut) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MsgOut) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto protoreflect.FileDescriptor

var file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDesc = []byte{
	0x0a, 0x57, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x68,
	0x6e, 0x73, 0x69, 0x69, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x62, 0x2f, 0x69,
	0x70, 0x63, 0x2f, 0x75, 0x64, 0x73, 0x2f, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x05, 0x4d, 0x73, 0x67,
	0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x4f, 0x75, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x68, 0x6e, 0x73, 0x69, 0x69, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x67,
	0x6f, 0x6c, 0x69, 0x62, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x75, 0x64, 0x73, 0x2f, 0x68, 0x69, 0x67,
	0x68, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescOnce sync.Once
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescData = file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDesc
)

func file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescGZIP() []byte {
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescOnce.Do(func() {
		file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescData)
	})
	return file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDescData
}

var file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_goTypes = []interface{}{
	(*MsgIn)(nil),  // 0: MsgIn
	(*MsgOut)(nil), // 1: MsgOut
}
var file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_init()
}
func file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_init() {
	if File_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_goTypes,
		DependencyIndexes: file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_depIdxs,
		MessageInfos:      file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_msgTypes,
	}.Build()
	File_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto = out.File
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_rawDesc = nil
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_goTypes = nil
	file_github_com_johnsiilver_golib_ipc_uds_highlevel_proto_stream_internal_proto_stream_proto_depIdxs = nil
}
