// Code generated by protoc-gen-go. DO NOT EDIT.
// source: io.proto

package input

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RescUri              string   `protobuf:"bytes,2,opt,name=resc_uri,json=rescUri,proto3" json:"resc_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b0773ef7c1937b, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Input) GetRescUri() string {
	if m != nil {
		return m.RescUri
	}
	return ""
}

type User struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b0773ef7c1937b, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *User) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Resource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b0773ef7c1937b, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Resource) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Perms struct {
	Read                 bool     `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write                bool     `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	Exec                 bool     `protobuf:"varint,3,opt,name=exec,proto3" json:"exec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Perms) Reset()         { *m = Perms{} }
func (m *Perms) String() string { return proto.CompactTextString(m) }
func (*Perms) ProtoMessage()    {}
func (*Perms) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b0773ef7c1937b, []int{3}
}

func (m *Perms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Perms.Unmarshal(m, b)
}
func (m *Perms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Perms.Marshal(b, m, deterministic)
}
func (m *Perms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Perms.Merge(m, src)
}
func (m *Perms) XXX_Size() int {
	return xxx_messageInfo_Perms.Size(m)
}
func (m *Perms) XXX_DiscardUnknown() {
	xxx_messageInfo_Perms.DiscardUnknown(m)
}

var xxx_messageInfo_Perms proto.InternalMessageInfo

func (m *Perms) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *Perms) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *Perms) GetExec() bool {
	if m != nil {
		return m.Exec
	}
	return false
}

// Output is the standard name for a Cog's output.
type Output struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Resc                 *Resource `protobuf:"bytes,3,opt,name=resc,proto3" json:"resc,omitempty"`
	Perms                *Perms    `protobuf:"bytes,4,opt,name=perms,proto3" json:"perms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b0773ef7c1937b, []int{4}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Output) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Output) GetResc() *Resource {
	if m != nil {
		return m.Resc
	}
	return nil
}

func (m *Output) GetPerms() *Perms {
	if m != nil {
		return m.Perms
	}
	return nil
}

func init() {
	proto.RegisterType((*Input)(nil), "input.Input")
	proto.RegisterType((*User)(nil), "input.User")
	proto.RegisterType((*Resource)(nil), "input.Resource")
	proto.RegisterType((*Perms)(nil), "input.Perms")
	proto.RegisterType((*Output)(nil), "input.Output")
}

func init() { proto.RegisterFile("io.proto", fileDescriptor_75b0773ef7c1937b) }

var fileDescriptor_75b0773ef7c1937b = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x51, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0xfd, 0xd2, 0x26, 0xa9, 0xbf, 0x4b, 0xf9, 0x21, 0x8b, 0x21, 0xb0, 0x50, 0x99, 0x81, 0x4e,
	0x19, 0x52, 0x89, 0x99, 0x85, 0x01, 0x16, 0x90, 0xa5, 0xce, 0x28, 0x24, 0x46, 0xb2, 0x54, 0x70,
	0x74, 0x76, 0x04, 0x5d, 0xf9, 0xcb, 0xd1, 0x9d, 0x1d, 0xb1, 0xbd, 0x17, 0xbf, 0x7b, 0xf7, 0xf2,
	0x0e, 0x84, 0x75, 0xcd, 0x88, 0x2e, 0x38, 0x59, 0xd8, 0xcf, 0x71, 0x0a, 0xea, 0x0e, 0x8a, 0x47,
	0x02, 0x52, 0x42, 0x3e, 0x79, 0x83, 0x75, 0xb6, 0xc9, 0xb6, 0xff, 0x35, 0x63, 0x79, 0x09, 0x02,
	0x8d, 0xef, 0x5f, 0x27, 0xb4, 0xf5, 0x82, 0xbf, 0xaf, 0x88, 0xef, 0xd1, 0xaa, 0x7b, 0xc8, 0xf7,
	0x24, 0xb9, 0x80, 0xe2, 0xdd, 0xa2, 0x0f, 0x69, 0x2e, 0x12, 0x32, 0x3b, 0x74, 0x3e, 0xa4, 0x21,
	0xc6, 0xf2, 0x14, 0x16, 0x76, 0xa8, 0x97, 0x9b, 0x6c, 0xbb, 0xd4, 0x0b, 0x3b, 0xa8, 0x27, 0x10,
	0xda, 0x78, 0x37, 0x61, 0x6f, 0x48, 0x1f, 0x8e, 0xa3, 0x99, 0x97, 0x13, 0x96, 0xe7, 0xb0, 0xfc,
	0xdb, 0x4b, 0x50, 0xd6, 0xb0, 0x1a, 0xbb, 0xe3, 0xc1, 0x75, 0xd1, 0x66, 0xad, 0x67, 0xaa, 0x1e,
	0xa0, 0x78, 0x31, 0xf8, 0xe1, 0xc9, 0x08, 0x4d, 0x37, 0xb0, 0x91, 0xd0, 0x8c, 0x29, 0xe2, 0x17,
	0xda, 0x60, 0xd8, 0x4a, 0xe8, 0x48, 0x48, 0x69, 0xbe, 0x4d, 0xcf, 0x4e, 0x42, 0x33, 0x56, 0x3f,
	0x19, 0x94, 0xcf, 0x53, 0xa0, 0x3a, 0x62, 0xda, 0x6c, 0x4e, 0x2b, 0xaf, 0x53, 0x3d, 0xe4, 0x51,
	0xb5, 0x55, 0xc3, 0xed, 0x35, 0x54, 0x41, 0xea, 0xea, 0x86, 0x36, 0xfb, 0xe8, 0x57, 0xb5, 0x67,
	0x49, 0x30, 0xff, 0xa1, 0xe6, 0x47, 0xa9, 0xa0, 0x18, 0x29, 0x67, 0x9d, 0xb3, 0x6a, 0x9d, 0x54,
	0x9c, 0x5d, 0xc7, 0xa7, 0x76, 0x47, 0xbd, 0xf4, 0x0e, 0x07, 0x83, 0xf2, 0x16, 0xca, 0x88, 0xe5,
	0x2c, 0xe5, 0x63, 0x5d, 0x9d, 0x24, 0x16, 0xc3, 0xaa, 0x7f, 0x6f, 0x25, 0x1f, 0x75, 0xf7, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0x46, 0xe4, 0x9b, 0xe0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecorderClient is the client API for Recorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecorderClient interface {
	Record(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type recorderClient struct {
	cc *grpc.ClientConn
}

func NewRecorderClient(cc *grpc.ClientConn) RecorderClient {
	return &recorderClient{cc}
}

func (c *recorderClient) Record(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/input.Recorder/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecorderServer is the server API for Recorder service.
type RecorderServer interface {
	Record(context.Context, *Input) (*Output, error)
}

func RegisterRecorderServer(s *grpc.Server, srv RecorderServer) {
	s.RegisterService(&_Recorder_serviceDesc, srv)
}

func _Recorder_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/input.Recorder/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServer).Record(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _Recorder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "input.Recorder",
	HandlerType: (*RecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _Recorder_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "io.proto",
}
